apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python 
    spec:
      containers:
      - name: python
        image: aptonaswin/concoures_repo:2.0.0
        ports:
        - containerPort: 8080
