apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: concourse-db
  name: concourse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: concourse
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: concourse
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /database
            - name: POSTGRES_DB
              value: concourse
            - name: POSTGRES_PASSWORD
              value: concourse_pass
            - name: POSTGRES_USER
              value: concourse_user
          image: postgres
          name: concourse-db
          resources: {}
      restartPolicy: Always
status: {}
